skip_repository_checks_reason: I want to skip repository checks
skip_license_checks_reason: I want to skip license checks
skip_registry_checks_reason: I want to skip registry checks
skip_citation_checks_reason: I want to skip citation checks
